server:
  port: 38080

spring:
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging.level:
  org.hibernate.SQL: debug


