server:
  port: 8080

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
